-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

local SCRIPTS_DIRECTORY = "~/.config/hypr/scripts"

-- Start XDG services


-- Start Polkit


-- Start the notification app


-- Load GTK settings


-- Start hypridle


-- Start Quickshell


-- Start blue-light filter


-- Start wallpaper handlers


-- start pywal restart


-- Start the hyprland dock


-- Start elephant


-- Start walker service


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/xdg.sh")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("swaync")
    hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("qs &")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hyprpaper & awww-daemon")
    hl.exec_cmd("~/.config/hypr/scripts/wal.sh")
    hl.exec_cmd("nwg-dock-hyprland -x")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
end)
