-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Cursors

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

-- XDG Desktop Portal

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- QT

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- GDK

hl.env("GDK_SCALE", 1)

-- Toolkit Backend

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("CLUTTER_BACKEND", "wayland")

-- Ozone

hl.env("OZONE_PLATFORM", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- Mozilla

hl.env("MOZ_ENABLE_WAYLAND", 1)
