-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manually fixed: fullscreen_state -> fullscreen, resizeactive -> resize

---@module 'hl'

--##################
--## MY PROGRAMS ###
--##################
-- See https://wiki.hyprland.org/Configuring/Keywords/

local SCRIPTS_DIRECTORY = "~/.config/hypr/scripts"

-- Set programs that you use
local terminal   = "kitty"
local fileManager = "nautilus"
local browser    = "brave"
local menu       = "walker"
local tor        = "tor-browser"
local editor     = "zeditor"
local wireShark  = "wireshark"

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER"
-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))
-- Open the termminal (default: kitty)

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("brave"))
-- Open the browser (default: brave)

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))
-- Open file manager (default: nautilus)

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("walker"))
-- Open ROFI menu

hl.bind(mainMod .. " + " .. "U", hl.dsp.exec_cmd("tor-browser"))
-- Open TOR browser

hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd("zeditor"))
-- Open Code editor (default: zed)

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("wireshark"))
-- Open Wireshark

hl.bind(mainMod .. " + " .. "PRINT", hl.dsp.exec_cmd("grimblast save screen"))
-- Save an image of the entire screen

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
-- Close active window

hl.bind(mainMod .. " + " .. "T", hl.dsp.window.float())
-- Turn active window to a floating one

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())
-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))
-- dwindle

hl.bind(mainMod .. " + " .. "K", hl.dsp.layout("swapsplit"))

hl.bind(mainMod .. " + " .. "left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down",  hl.dsp.focus({ direction = "down" }))

-- FIXED: resizeactive -> hl.dsp.window.resize({ x, y, relative = true })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 100,  y = 0,    relative = true }))
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.resize({ x = -100, y = 0,    relative = true }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.resize({ x = 0,    y = 100,  relative = true }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.resize({ x = 0,    y = -100, relative = true }))

-- FIXED: fullscreen_state(N) -> fullscreen({ mode = N })
hl.bind(mainMod .. " + " .. "F", function()
    local w = hl.get_active_window()
    if w ~= nil and w.fullscreen == 2 then
        -- currently in our custom fullscreen state, exit it
        hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 0, client = 0, action = "set" }))
    else
        -- not fullscreen, enter our custom state
        hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 2, client = 0, action = "set" }))
    end
end)

hl.bind(mainMod .. " + " .. "M", function()
    local w = hl.get_active_window()
    if w ~= nil and w.fullscreen == 1 then
        -- currently maximized, exit it
        hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 0, client = 0, action = "set" }))
    else
        -- not maximized, maximize it
        hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 1, client = 0, action = "set" }))
    end
end)
--hl.bind(mainMod .. " + " .. "F", function()
--    hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 2, client = 0, action = "set" }))
--end)
--hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen({ mode = 0 }))
-- Toggle real fullscreen

--hl.bind(mainMod .. " + " .. "M", hl.dsp.window.fullscreen({ mode = 1 }))
-- Toggle maximize

-- Switch workspaces n [0 <= n <= 9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace n [0 <= n <= 9]
hl.bind(mainMod .. " + SHIFT + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Move all windows to workspace n [0 <= n <= 9]
hl.bind(mainMod .. " + CTRL + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 1"))
hl.bind(mainMod .. " + CTRL + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 2"))
hl.bind(mainMod .. " + CTRL + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 3"))
hl.bind(mainMod .. " + CTRL + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 4"))
hl.bind(mainMod .. " + CTRL + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 5"))
hl.bind(mainMod .. " + CTRL + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 6"))
hl.bind(mainMod .. " + CTRL + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 7"))
hl.bind(mainMod .. " + CTRL + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 8"))
hl.bind(mainMod .. " + CTRL + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 9"))
hl.bind(mainMod .. " + CTRL + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveAllTo.sh 10"))

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.config({
    binds = {
        movefocus_cycles_fullscreen = 1,
    },
})
