-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- Ignore maximize requests from apps. You'll probably like this.

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "brave-browser",
    match = {
        class = "(Brave-browser)",
    },
    tile = true,
})

hl.window_rule({
    name  = "chromium",
    match = {
        class = "(Chromium)",
    },
    tile = true,
})

hl.window_rule({
    name  = "kitty",
    match = {
        class = "^(kitty)$",
    },
    tile = true,
})

-- hyprpwcenter

hl.window_rule({
    name  = "hyprpwcenter",
    match = {
        class = "(hyprpwcenter)",
    },
    float = true,
    size = { 500, 550 },
    center = true,
    pin = true,
})

-- Blueman Manager

hl.window_rule({
    name  = "blueman-manager",
    match = {
        class = "(blueman-manager)",
    },
    float = true,
    size = { 800, 600 },
    center = true,
})

-- nwg-look

hl.window_rule({
    name  = "nwglook",
    match = {
        class = "(nwg-look)",
    },
    float = true,
    size = { 700, 600 },
    move = { "10%", "20%" },
    pin = true,
})

-- nwg-displays

hl.window_rule({
    name  = "nwgdisplays",
    match = {
        class = "(nwg-displays)",
    },
    float = true,
    size = { 900, 600 },
    move = { "10%", "20%" },
    pin = true,
})

-- Gnome Calculator

hl.window_rule({
    name  = "calculator",
    match = {
        class = "(org.gnome.Calculator)",
    },
    float = true,
    size = { 700, 600 },
    center = true,
})

-- Idle Inhibit

hl.window_rule({
    name  = "idle-inhibit",
    match = {
        class = ".*",
    },
    idle_inhibit = "fullscreen",
})
