# hyprlauncher configuration file
# For more info, see the Hyprland Wiki: https://wiki.hypr.land/Hypr-Ecosystem/hyprlauncher/

general {
    # If the launcher should grab full keyboard focus on opening (default: true)
    grab_focus = true
}

cache {
    # If modules should maintain a cache of frequently used entries (default: true)
    cache = true
}

# UI configuration options
ui {
    # Set the window size (width height)
    window_size = 600 400
}

# Finder prefixes
finders {
    # Set the default finder (desktop, unicode, math) (default: desktop)
    default_finder = desktop

    # Enable or disable icons in search results (default: true)
    desktop_icons = true

    # Prefix for the desktop finder (leave empty to make it the default)
    desktop_prefix =

    # Prefix for the unicode finder (default: .)
    unicode_prefix = .

    # Prefix for the math finder (default: =)
    math_prefix = =
}
