# Theme settings
color_scheme =
icon_theme = Papirus
style = Breeze
font_fixed = JetBrainsMono Nerd Font
font_fixed_size = 11
font = JetBrainsMono Nerd Font
font_size = 11

# Miscellaneous settings
single_click_activate = true
menus_have_icons = true
shortcuts_for_context_menus = true
