# Theme settings
theme {
    style = Fusion
    color_scheme = /usr/share/qt6ct/colors/darker.conf
    icon_theme = breeze-dark
    font_fixed = DejaVu LGC Sans
    font_fixed_size = 12
    font = DejaVu LGC Sans
    font_size = 12
}


# Miscellaneous settings
misc {
    single_click_activate = true
    menus_have_icons = true
    shortcuts_for_context_menus = false

}
