-- ~/.config/hypr/colors.lua  (generated by matugen — don't hand-edit)
return {
    background = "rgb({{colors.background.default.hex_stripped}})",
    foreground = "rgb({{colors.on_background.default.hex_stripped}})",
    primary    = "rgb({{colors.primary.default.hex_stripped}})",
    accent     = "rgb({{colors.tertiary.default.hex_stripped}})",
    surface    = "rgb({{colors.surface.default.hex_stripped}})",
    outline    = "rgb({{colors.outline.default.hex_stripped})}",
}
