-- ~/.config/hypr/colors.lua  (generated by matugen — don't hand-edit)
return {
    background = "rgba({{colors.background.default.hex_stripped}})",
    foreground = "rgba({{colors.on_background.default.hex_stripped}})",
    primary    = "rgba({{colors.primary.default.hex_stripped}})",
    accent     = "rgba({{colors.tertiary.default.hex_stripped}})",
    surface    = "rgba({{colors.surface.default.hex_stripped}})",
}
