# Foreground and Background
foreground           #{{colors.on_background.default.hex_stripped}}
background           #{{colors.background.default.hex_stripped}}
selection_foreground #{{colors.background.default.hex_stripped}}
selection_background #{{colors.on_background.default.hex_stripped}}
# Cursor colors
cursor               #{{colors.on_background.default.hex_stripped}}
cursor_text_color    #{{colors.background.default.hex_stripped}}
# The 16 terminal colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
color0  #{{base16.base00.default.hex_stripped}}
color1  #{{base16.base08.default.hex_stripped}}
color2  #{{base16.base0b.default.hex_stripped}}
color3  #{{base16.base0a.default.hex_stripped}}
color4  #{{base16.base0d.default.hex_stripped}}
color5  #{{base16.base0e.default.hex_stripped}}
color6  #{{base16.base0c.default.hex_stripped}}
color7  #{{base16.base05.default.hex_stripped}}
# Bright variants
color8  #{{base16.base03.default.hex_stripped}}
color9  #{{base16.base08.default.hex_stripped}}
color10 #{{base16.base0b.default.hex_stripped}}
color11 #{{base16.base0a.default.hex_stripped}}
color12 #{{base16.base0d.default.hex_stripped}}
color13 #{{base16.base0e.default.hex_stripped}}
color14 #{{base16.base0c.default.hex_stripped}}
color15 #{{base16.base05.default.hex_stripped}}
