# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}


# Fix some dragging issues with XWayland
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = brave-browser
    match:class = (Brave-browser)
    tile = on
}

windowrule {
    name = chromium
    match:class = (Chromium)
    tile = on
}

windowrule {
    name = kitty
    match:class = ^(kitty)$
    tile = on
}

# hyprpwcenter
windowrule {
    name = hyprpwcenter
    match:class = (hyprpwcenter)
    float = on
    size = 700 600
    center = on
    pin = on
}

# Blueman Manager
windowrule {
    name = blueman-manager
    match:class = (blueman-manager)
    float = on
    size = 800 600
    center = on
}

# nwg-look
windowrule {
    name = nwglook
    match:class = (nwg-look)
    float = on
    size = 700 600
    move = 10% 20%
    pin = on
}

# nwg-displays
windowrule {
    name = nwgdisplays
    match:class = (nwg-displays)
    float = on
    size = 900 600
    move = 10% 20%
    pin = on
}

# Gnome Calculator
windowrule {
    name = calculator
    match:class = (org.gnome.Calculator)
    float = on
    size = 700 600
    center = on
}

# Idle Inhibit
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = idle-inhibit
    match:class = .*
    idle_inhibit = fullscreen
}
