[general]
import = ["/home/iparchnuke/.cache/wal/alacritty.toml"]
live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[colors.primary]
foreground = "#121212"
background = "#f2db8a"

[colors.normal]
black = "#121212"
red = "#665219"
green = "#90721B"
yellow = "#B08D1F"
blue = "#D2A617"
magenta = "#F2BB06"
cyan = "#FCC60B"
white = "#f2db8a"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
